version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - sonarcloud/scan-on-branch-commit:
          cache-version: v0
          github-project-slug: socialtables/lazy-load-frontend
          project-key: VictorMCL_lazy-load-frontend
orbs:
  sonarcloud: socialtables/sonarcloud@1.0.0

workflows:
  main:
    jobs:
      - build:
          context: st-global
          filters:
            tags:
              only: /.*/
