version: 2 
jobs:
  build:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: install dependencies
          command: npm install
      - run: 
          name: build
          command: npm run build
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0 
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud