version: 2.1

jobs:
  Build:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .  

  Unit Test:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Unit Test
          command: |
            ls
            echo "Testing"

  Static Code Analysis:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - sonarcloud/scan

  Build and Upload Docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t victormcl/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM .
      - run:
          name: Login Docker HUB
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker image
          command: docker push victormcl/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BUILD_NUM

  Cloning repositoriy CD:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/CD
    steps:
      - add_ssh_keys:
          fingerprints:
            - "40:e1:81:a2:fc:ea:0c:98:c0:a3:8e:74:f0:ed:38:0a"
      - run:
          name: Clone frontend repository
          command: git clone git@github.com:VictorMCL/python-flask.git --non-interactive

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      #- Build:
      #    context: sonarcloud
      #- Unit Test:
      #    context: sonarcloud
      #    requires:
      #      - Build
      #- Static Code Analysis:
      #    context: sonarcloud
      #    requires:
      #      - Unit Test
      #- Build and Upload Docker:
      #    context: sonarcloud
      #    requires:
      #      - Static Code Analysis
      #    filters:
      #      branches:
      #        only: master
      - Cloning repositoriy CD