version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      #- run:
      #    name: update-npm
      #    command: 'sudo npm install -g npm@5'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: install dependencies
          command: npm install
      - run: 
          name: build
          command: |
            npm run build
            ls 
            pwd