jobs:
  build:
    docker:
      - image: 'circleci/node:10.16.3'
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - sonarcloud/scan-on-branch-commit:
          cache-version: v0
          github-project-slug: socialtables/my-project
          project-key: socialtables_my-project
orbs:
  sonarcloud: socialtables/sonarcloud@1.1.0
version: 2.1
workflows:
  build-deploy:
    jobs:
      - build:
          context: st-global
          filters:
            tags:
              only: /.*/
  version: 2