version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: install dependencies
          command: npm install
      - run: 
          name: build
          command: npm run build
      - persist_to_workspace:
          root: /root/project
          paths:
            - echo-output

  static code analysis:
    docker:
      - image: circleci/node:12.14
    steps:
      - attach_workspace:
          at: /root/project
      - run: ls
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
      - static code analysis:
          requires:
            - build
          context: sonarcloud